version: '3.9'

services:
  db:
    image: postgres:17
    container_name: drug_db
    restart: always
    environment:
      POSTGRES_USER: khangdoan
      POSTGRES_PASSWORD: khangdoan
      POSTGRES_DB: drugdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: drug_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db
    volumes:
      - .:/app

  frontend:
    build: ../frontend/drugscan-react-app
    container_name: drug_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
